In [1]:
import numpy as np
import pandas as pd

In [3]:
data = pd.read_csv('IMDB Dataset.csv')

In [4]:
data.head(5)

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
data['sentiment'].value_counts()

positive    25000
negative    25000
Name: sentiment, dtype: int64

In [9]:
data['review'].head(5)

0    One of the other reviewers has mentioned that ...
1    A wonderful little production. <br /><br />The...
2    I thought this was a wonderful way to spend ti...
3    Basically there's a family where a little boy ...
4    Petter Mattei's "Love in the Time of Money" is...
Name: review, dtype: object

In [11]:
for c in data[data['sentiment'] == 'positive']['review'].head(5):
  print(c)

One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fac

In [13]:
data.sentiment

0        positive
1        positive
2        positive
3        negative
4        positive
           ...   
49995    positive
49996    negative
49997    negative
49998    negative
49999    negative
Name: sentiment, Length: 50000, dtype: object

In [16]:
data['sentiment'] = data['sentiment'].map({'positive': 1, 'negative': 0})

In [17]:
data.head(5)

review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

**BOW -- Bag of Words**

In [19]:
from scipy.sparse import csr_matrix

In [22]:
a = np.zeros([5, 5])
a[2, 2] = 5
a[4, 4] = 6
a[0, 3] = 1
a[3, 1] = 4
a[3, 2] = 2
a[1, 1] = 7

In [23]:
a

array([[0., 0., 0., 1., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 4., 2., 0., 0.],
       [0., 0., 0., 0., 6.]])

In [25]:
pd.DataFrame(a, columns=['apple', 'wax', 'sadness', 'luck', 'girl'])

apple  wax  sadness  luck  girl
0    0.0  0.0      0.0   1.0   0.0
1    0.0  7.0      0.0   0.0   0.0
2    0.0  0.0      5.0   0.0   0.0
3    0.0  4.0      2.0   0.0   0.0
4    0.0  0.0      0.0   0.0   6.0

In [26]:
b = csr_matrix(a)

In [27]:
b

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 6 stored elements in Compressed Sparse Row format>

In [28]:
b.todense()

matrix([[0., 0., 0., 1., 0.],
        [0., 7., 0., 0., 0.],
        [0., 0., 5., 0., 0.],
        [0., 4., 2., 0., 0.],
        [0., 0., 0., 0., 6.]])

In [29]:
b.nonzero()

(array([0, 1, 2, 3, 3, 4], dtype=int32),
 array([3, 1, 2, 1, 2, 4], dtype=int32))

In [30]:
b.data

array([1., 7., 5., 4., 2., 6.])

In [36]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

In [38]:
train_df, test_df = train_test_split(data, test_size=0.5)

In [39]:
len(train_df)

25000

In [40]:
train_df['sentiment'].value_counts()

0    12528
1    12472
Name: sentiment, dtype: int64

In [64]:
%%time
cv = CountVectorizer(ngram_range=(1, 2))
X_train_sparse = cv.fit_transform(train_df['review'])

CPU times: user 20.8 s, sys: 699 ms, total: 21.5 s
Wall time: 21.6 s


In [65]:
cv.vocabulary_

{'the': 1293191,
 'peace': 989268,
 'and': 66313,
 'beauty': 153695,
 'of': 918479,
 'koyaanisqatsi': 741064,
 'was': 1436398,
 'powerful': 1026864,
 'affirmation': 35472,
 'natural': 883737,
 'world': 1498244,
 'in': 655863,
 'naqoyqatsi': 881835,
 'we': 1447938,
 'are': 100929,
 'assaulted': 120206,
 'by': 223353,
 'images': 650673,
 'synthetic': 1266142,
 'competitive': 292661,
 'violent': 1425878,
 'digital': 366377,
 'destructive': 357742,
 'constructs': 302770,
 'our': 964959,
 'culture': 328679,
 'br': 197320,
 'some': 1199918,
 'liberties': 763697,
 'taken': 1268190,
 'with': 1481896,
 'posterization': 1025284,
 'distressing': 377344,
 'much': 869103,
 'slow': 1189063,
 'motion': 860593,
 'connections': 299612,
 'between': 171820,
 'sequences': 1151299,
 'inscrutable': 674643,
 'if': 647609,
 'there': 1322552,
 'any': 92498,
 'is': 689118,
 'defined': 347576,
 'at': 121857,
 'film': 479214,
 'end': 418921,
 'missed': 844071,
 'opportunity': 952914,
 'to': 1349860,
 'place': 100

In [66]:
len(cv.vocabulary_)

1519400

In [67]:
%%time
X_test_sparce = cv.transform(test_df.review)

CPU times: user 12.8 s, sys: 43.1 ms, total: 12.8 s
Wall time: 12.9 s


In [68]:
X_train_sparse.shape, X_test_sparce.shape

((25000, 1519400), (25000, 1519400))

In [69]:
X_train_sparse

<25000x1519400 sparse matrix of type '<class 'numpy.int64'>'
	with 8698071 stored elements in Compressed Sparse Row format>

In [70]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.metrics import accuracy_score

In [71]:
y_train, y_test = train_df.sentiment, test_df.sentiment  

In [72]:
np.bincount(y_train), np.bincount(y_test)

(array([12528, 12472]), array([12472, 12528]))

In [73]:
logit = LogisticRegression(random_state=17, n_jobs=-1)
sgd_logit = SGDClassifier(max_iter=40, random_state=17, n_jobs=-1)

In [74]:
10 ** 6 / X_train_sparse.shape[0]

40.0

In [75]:
%%time
logit.fit(X_train_sparse, y_train)

CPU times: user 1.04 s, sys: 214 ms, total: 1.25 s
Wall time: 45.6 s


LogisticRegression(n_jobs=-1, random_state=17)

In [76]:
%%time
sgd_logit.fit(X_train_sparse, y_train)

CPU times: user 2.72 s, sys: 132 ms, total: 2.86 s
Wall time: 2.74 s


SGDClassifier(max_iter=40, n_jobs=-1, random_state=17)

In [77]:
accuracy_score(y_test, logit.predict(X_test_sparce))

0.89852

In [78]:
accuracy_score(y_test, sgd_logit.predict(X_test_sparce))

0.88184

In [83]:
hash('be very nice.') % 10 ** 6

89699